name: dancer-net
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - librosa
  - numpy
  - pandas
  - bs4
  - requests
  - tqdm
  - pytorch-lightning
  - rich
  - scikit-learn
  - tensorboard
  - transformers
  - accelerate
  - pytest
