name: dancer-net
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - bs4
  - requests
  - bidict
  - tqdm
  - pytorch-lightning
  - rich
  - scikit-learn
  - tensorboard
  - pip:
      - git+https://github.com/huggingface/transformers.git
      - evaluate
      - wakepy
