name: dancer-net
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - librosa
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - bs4
  - requests
  - bidict
  - tqdm
  - pytorch-lightning
  - rich
  - scikit-learn
  - tensorboard
  - transformers
  - accelerate
  - pytest

  - pip:
      - evaluate
      - wakepy
      - soundfile
      - youtube_dl
