weight_path: lightning_logs/version_0/checkpoints/epoch=5-step=870.ckpt
expected_duration: 6
threshold: 0.5
resample_frequency: 16000
device: cpu
labels:
  - Argentine Tango
  - Balboa
  - Bachata
  - Blues
  - Cha Cha
  - Cumbia
  - Carolina Shag
  - East Coast Swing
  - Hustle
  - Jive
  - Lindy Hop
  - Quickstep
  - Rumba
  - Slow Foxtrot
  - Salsa
  - Samba
  - Slow Waltz
  - Tango (Ballroom)
  - Viennese Waltz
  - West Coast Swing
