weight_path: models/weights/ResidualDancer/weights.ckpt
expected_duration: 6
threshold: 0.4
resample_frequency: 16000
device: cpu
labels:
  - Argentine Tango
  - Bachata
  - Cha Cha
  - East Coast Swing
  - Hustle
  - Jive
  - Quickstep
  - Rumba
  - Slow Foxtrot
  - Salsa
  - Samba
  - Slow Waltz
  - Tango (Ballroom)
  - Viennese Waltz
